board/urls.py
from django.urls import path
from . import views

app_name = 'board'
urlpatterns = [
    path("", views.board_list, name='board_list'),
    path("write", views.board_write, name='board_write'),
    path("detail/<int:pk>/", views.board_detail, name='board_detail'),
    path("detail/<int:pk>/delete/", views.board_delete, name='board_delete'),
    path("detail/<int:pk>/modify/", views.board_modify, name='board_modify'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("main/", include("firstapp.urls")),
    path("", RedirectView.as_view(url="/main/", permanent=True)),
    path("user/", include("user.urls")),
    path("board/", include("board.urls")),
    path("todo/", include("todo.urls")),
]

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstapp/urls.py
from django.urls import path
from firstapp import views

app_name = 'todo_main'
urlpatterns = [
    path("", views.main_page, name='main_page'),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path("item/", views.todo_main, name='todo_main'),
    path("update/", views.update_todo, name='update_todo'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    path("RegisterAndLogin/", views.RegisterAndLogin, name='RegisterAndLogin'),
    path("logout/", views.logout, name='logout'),
    path("myinfo/", views.Myinfo, name='myinfo'),

    
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="user/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_done.html"),
         name="password_reset_complete"),
]

firstapp/models.py
from django.db import models

firstapp/views.py
from django.shortcuts import render, HttpResponse
from user.models import User

def main_page(request):
    login_session = request.session.get('login_session','')
    context = { 'login_session' : login_session }
    
    if login_session == '':
        context['login_session'] = False
    else:
        context['login_session'] = True
    
    return render(request, 'firstapp/index.html', context)

firstapp/templates/firstapp/index back_up.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.css" rel="stylesheet"/>
    <style>
        .center {
            /* background: linear-gradient(to bottom right, #a2f5c4,#ffffff); */
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100;
        }
        .title {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="center">
        <div>
            <a href="{% url 'todo_main:main_page' %}" class=""><h1>TODO_LIST</h1></a>
        </div>
    </div>
    <div class="center">
    {% if login_session %}
    <a href="{% url 'todo:todo_main' %}"><button type="button" class="btn btn-outline-dark">TODO_LIST</button></a>
    <a href="{% url 'board:board_list' %}"><button type="button" class="btn btn-outline-dark">게시판</button></a>
    <a href="{% url 'user:logout' %}"><button type="button" class="btn btn-outline-dark">로그아웃</button></a>
    {% else %}
    <a href="{% url 'user:login' %}"><button type="button" class="btn btn-outline-dark">로그인</button></a>
    <a href="{% url 'user:register' %}"><button type="button" class="btn btn-outline-dark">회원가입</button></a>
    {% endif %}
    </div>
    {% block contents %}
    {% endblock contents %}
</body>
</html>

firstapp/templates/firstapp/index copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.3.0/mdb.min.css" rel="stylesheet"/>
    <title>Document</title>
</head>
<body>
    <section class="vh-100" style="background-color: #e2d5de;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
      
              <div class="card" style="border-radius: 15px;">
                <div class="card-body p-5">
      
                  <h6 class="mb-3">Awesome Todo List</h6>
      
                  <form class="d-flex justify-content-center align-items-center mb-4">
                    <div class="form-outline flex-fill">
                      <input type="text" id="form3" class="form-control form-control-lg" />
                      <label class="form-label" for="form3">What do you need to do today?</label>
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg ms-2">Add</button>
                  </form>
      
                  <ul class="list-group mb-0">
                    <li
                      class="list-group-item d-flex justify-content-between align-items-center border-start-0 border-top-0 border-end-0 border-bottom rounded-0 mb-2">
                      <div class="d-flex align-items-center">
                        <input class="form-check-input me-2" type="checkbox" value="" aria-label="..." />
                        Cras justo odio
                      </div>
                      <a href="#!" data-mdb-toggle="tooltip" title="Remove item">
                        <i class="fas fa-times text-primary"></i>
                      </a>
                    </li>
                    <li
                      class="list-group-item d-flex d-flex justify-content-between align-items-center border-start-0 border-top-0 border-end-0 border-bottom rounded-0 mb-2">
                      <div class="d-flex align-items-center">
                        <input class="form-check-input me-2" type="checkbox" value="" aria-label="..." checked />
                        <s>Dapibus ac facilisis in</s>
                      </div>
                      <a href="#!" data-mdb-toggle="tooltip" title="Remove item">
                        <i class="fas fa-times text-primary"></i>
                      </a>
                    </li>
                    <li
                      class="list-group-item d-flex d-flex justify-content-between align-items-center border-start-0 border-top-0 border-end-0 border-bottom rounded-0 mb-2">
                      <div class="d-flex align-items-center">
                        <input class="form-check-input me-2" type="checkbox" value="" aria-label="..." />
                        Morbi leo risus
                      </div>
                      <a href="#!" data-mdb-toggle="tooltip" title="Remove item">
                        <i class="fas fa-times text-primary"></i>
                      </a>
                    </li>
                    <li
                      class="list-group-item d-flex d-flex justify-content-between align-items-center border-start-0 border-top-0 border-end-0 border-bottom rounded-0 mb-2">
                      <div class="d-flex align-items-center">
                        <input class="form-check-input me-2" type="checkbox" value="" aria-label="..." />
                        Porta ac consectetur ac
                      </div>
                      <a href="#!" data-mdb-toggle="tooltip" title="Remove item">
                        <i class="fas fa-times text-primary"></i>
                      </a>
                    </li>
                    <li
                      class="list-group-item d-flex d-flex justify-content-between align-items-center border-start-0 border-top-0 border-end-0 border-bottom rounded-0 mb-0">
                      <div class="d-flex align-items-center">
                        <input class="form-check-input me-2" type="checkbox" value="" aria-label="..." checked />
                        Vestibulum at eros
                      </div>
                      <a href="#!" data-mdb-toggle="tooltip" title="Remove item">
                        <i class="fas fa-times text-primary"></i>
                      </a>
                    </li>
                    <li
                      class="list-group-item d-flex justify-content-between align-items-center border-start-0 border-top-0 border-end-0 border-bottom rounded-0 mb-2">
                      <div class="d-flex align-items-center">
                        <input class="form-check-input me-2" type="checkbox" value="" aria-label="..." />
                        Morbi leo risus
                      </div>
                      <a href="#!" data-mdb-toggle="tooltip" title="Remove item">
                        <i class="fas fa-times text-primary"></i>
                      </a>
                    </li>
                  </ul>
      
                </div>
              </div>
      
            </div>
          </div>
        </div>
    </section>
</body>
</html>

firstapp/templates/firstapp/index.html
<!DOCTYPE html>
<html lang="kr">

<head>
    <meta charset="UTF-8">
    <title>Green House</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/static/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-light px-4 px-lg-5 py-3 py-lg-0">
                <a href="{% url 'todo_main:main_page' %}" class="navbar-brand p-0">
                    <h1 class="m-0">To Do Today</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0">
                        <a href="{% url 'todo_main:main_page' %}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'todo:todo_main' %}" class="nav-item nav-link">Today_list</a>
                        <a href="{% url 'board:board_list' %}" class="nav-item nav-link">board</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu m-0">
                                <a href="feature.html" class="dropdown-item">Update Soon</a>
                                <a href="quote.html" class="dropdown-item">Update Soon</a>
                                <a href="team.html" class="dropdown-item">Update Soon</a>
                                <a href="testimonial.html" class="dropdown-item">Update Soon</a>
                                <a href="404.html" class="dropdown-item">Update Soon</a>
                            </div>
                        </div>
                        <a href="{% url 'user:myinfo' %}" class="nav-item nav-link">My info</a>
                    </div>
                    {% if login_session %}
                    <a href="{% url 'user:logout' %}" class="btn btn-light rounded-pill text-primary py-2 px-4 ms-lg-5">로그아웃</a>
                    {% else %}
                    <a href="{% url 'user:RegisterAndLogin' %}" class="btn btn-light rounded-pill text-primary py-2 px-4 ms-lg-5">로그인</a>
                    {% endif %}
                </div>
            </nav>

            <div class="container-xxl bg-primary hero-header">
                <div class="container">
                    <div class="row g-5 align-items-center">
                        <div class="col-lg-6 text-center text-lg-start">
                            <h1 id="mainHeading" class="text-white mb-4 animated zoomIn" >오늘 해야 할 일들을 정리해 보세요!</h1>
                            <p id="subHeading1" class="text-white pb-3 animated zoomIn">게시판 "board"를 이용해 글을 기록할 수 있습니다</p>
                            <p id="subHeading2" class="text-white pb-4 animated zoomIn">
                                <i class="fa-solid fa-triangle-exclamation fa-beat-fade"> Update soon</i><br>
                                + Calendar, Scheduler<br>
                                + 내 정보 페이지 세부기능<br>
                            </p>
                            <div class="d-flex justify-content-center">
                            <a href="{% url 'todo:todo_main' %}" class="btn btn-outline-light rounded-pill border-2 py-3 px-5 animated slideInRight">Go Todo!</a>
                            </div>
                        </div>
                        <div class="col-lg-6 text-center text-lg-start">
                            <img class="img-fluid animated zoomIn" src="/static/img/green.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->

        


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    
    
    
    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/lib/wow/wow.min.js"></script>
    <script src="/static/lib/easing/easing.min.js"></script>
    <script src="/static/lib/waypoints/waypoints.min.js"></script>
    <script src="/static/lib/owlcarousel/owl.carousel.min.js"></script>
    
    <!-- Template Javascript -->
    <script src="/static/js/main.js"></script>
    
</body>
</html>