config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("main/", include("firstapp.urls")),
    path("", RedirectView.as_view(url="/main/", permanent=True)),
    path("user/", include("user.urls")),
    path("board/", include("board.urls")),
    path("todo/", include("todo.urls")),
]

urlpatterns += [path('summernote/', include('django_summernote.urls'))]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path("item/", views.todo_main, name='todo_main'),
    path("update/", views.update_todo, name='update_todo'),
]

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'user'
urlpatterns = [
    path("RegisterAndLogin/", views.RegisterAndLogin, name='RegisterAndLogin'),
    path("logout/", views.logout, name='logout'),
    path("myinfo/", views.Myinfo, name='myinfo'),

    
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name="user/password_reset.html"),
         name="reset_password"),

    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="user/password_reset_sent.html"),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="user/password_reset_form.html"),
         name="password_reset_confirm"),

    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="user/password_reset_done.html"),
         name="password_reset_complete"),
]

user/models.py
from django.db import models

class User(models.Model):
    user_id = models.CharField(max_length=40, unique=True, verbose_name='유저 아이디')
    user_pw = models.CharField(max_length=130, verbose_name='유저 비밀번호')
    user_pw_confirm = models.CharField(max_length=130, verbose_name='비밀번호 확인', null=True)
    user_name = models.CharField(max_length=20, unique=True, verbose_name='유저 이름')
    user_email = models.EmailField(max_length=130, unique=True, verbose_name='유저 이메일')
    user_register_dttm = models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')

    def __str__(self):
        return self.user_name

    class Meta:
        db_table = 'sign_up'
        verbose_name = '유저관리'
        verbose_name_plural = '유저관리'

user/forms.py
from django import forms
from .models import User
from argon2 import PasswordHasher, exceptions
# from django.contrib.auth.models import User

class RegisterFrom(forms.ModelForm):
    user_id = forms.CharField(
        label='아이디',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '아이디'
            }
        ),
        error_messages={
        'required' : '아이디를 입력해주세요.',
        'unique' : '중복된 아이디 입니다.'}
    )
    user_pw = forms.CharField(
        label='비밀번호',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '비밀번호'
            }
        ),
        error_messages={'required' : '비밀번호를 입력해주세요.'}
    )
    user_pw_confirm = forms.CharField(
        label='비밀번호 확인',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '비밀번호 확인'
            }
        ),
        error_messages={'required' : '비밀번호 를 다시 확인해주세요.'}
    )
    user_name = forms.CharField(
        label='이름',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '이름'
            }
        ),
        error_messages={
        'required' : '닉네임을 입력해주세요.',
        'unique' : '중복된 이름 입니다.'}
    )
    user_email = forms.EmailField(
        label='이메일',
        required=True,
        widget=forms.EmailInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '이메일'
            }
        ),
        error_messages={
        'required' : '이메일을 입력해주세요',
        'unique' : '중복된 이메일 입니다.'}
    )
    field_order = [
        'user_id',
        'user_pw',
        'user_pw_confirm',
        'user_name',
        'user_email'
    ]

    class Meta:
        model = User
        fields = [
            'user_id',
            'user_pw',
            'user_name',
            'user_email'
        ]
    
    def clean(self):
        cleaned_data = super().clean()

        user_id = cleaned_data.get('user_id','')
        user_pw = cleaned_data.get('user_pw','')
        user_pw_confirm = cleaned_data.get('user_pw_confirm','')
        user_name = cleaned_data.get('user_name','')
        user_email = cleaned_data.get('user_email','')

        if user_pw != user_pw_confirm:
            return self.add_error('user_pw_confirm', '비밀번호가 다릅니다.')
        elif not (4 <= len(user_id) <= 16):
            return self.add_error('user_id', '아이디는 4~16자 이내로 입력해 주세요.')
        elif 8 > len(user_pw):
            return self.add_error('user_pw', '비밀번호는 8자 이상으로 입력해 주세요.')
        else:
            self.user_id = user_id
            self.user_pw = PasswordHasher().hash(user_pw)
            self.user_pw_confirm = PasswordHasher().hash(user_pw_confirm)
            self.user_name = user_name
            self.user_email = user_email

class LoginForm(forms.Form):
    user_id = forms.CharField(
        max_length=40,
        label='아이디 작성란',
        required=True,
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'placeholder' :'아이디'
            }
        ),
        error_messages={'required' : '아이디를 입력해주세요.'}
    )
    user_pw = forms.CharField(
        max_length=128,
        label='비밀번호',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class' : 'form-control',
                'placeholder' : '비밀번호'
            }
        ),
        error_messages={'required' : '비밀번호를 입력해주세요.'}
    )

    field_order = [
        'user_id',
        'user_pw',
    ]

    def clean(self):
        cleaned_data = super().clean()

        user_id = cleaned_data.get('user_id','')
        user_pw = cleaned_data.get('user_pw','')

        if user_id == '':
            return self.add_error('user_id', '아이디를 다시 입력해주세요.')
        elif user_pw =='':
            return self.add_error('user_pw','비밀번호를 다시 입력해 주세요.')
        else:
            try:
                user = User.objects.get(user_id=user_id)
            except User.DoesNotExist:
                return self.add_error('user_id', '아이디가 존재하지 않습니다')
            
            try:
                PasswordHasher().verify(user.user_pw, user_pw)
            except exceptions.VerifyMismatchError:
                return self.add_error('user_pw', '비밀번호가 다릅니다')
            
            self.login_session = user.user_id

user/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from user.decorators import login_required
from .models import User
from django.db import transaction
from argon2 import PasswordHasher
from .forms import RegisterFrom, LoginForm
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

@login_required
def Myinfo(request):
    login_session = request.session.get('login_session', '')
    context = { 'login_session' : login_session }

    user = User.objects.get(user_id=login_session)

    context = {
        'user_name': user.user_name,
        'user_email': user.user_email,
        'user_id': user.user_id,
    }

    return render(request, 'user/myinfo.html', context)


def RegisterAndLogin(request):
    loginforms = LoginForm()
    registerforms = RegisterFrom()
    context = { 'loginforms' : loginforms,
               'registerforms' : registerforms,}

    if request.method == 'GET':
        return render(request, 'user/login.html', context)
    
    elif 'login' in request.POST:
        loginforms = LoginForm(request.POST)

        if loginforms.is_valid():
            request.session['login_session'] = loginforms.login_session
            request.session.set_expiry(0)
            return redirect('/')
        else:
            context['loginforms'] = loginforms
            
            if loginforms.errors:
                for login_value in loginforms.errors.values():
                    context['login_error'] = login_value
        return render(request, 'user/login.html', context)
    
    elif 'register' in request.POST:
        registerforms = RegisterFrom(request.POST)

        if registerforms.is_valid():
            user = User(
                user_id = registerforms.user_id,
                user_pw = registerforms.user_pw,
                user_pw_confirm = registerforms.user_pw_confirm,
                user_name = registerforms.user_name,
                user_email = registerforms.user_email,
            )
            user.save()
            return redirect('/user/RegisterAndLogin/')
        else:
            context['registerforms'] = registerforms

            if registerforms.errors:
                for register_value in registerforms.errors.values():
                    context['registerforms_error'] = register_value
        return render(request, 'user/login.html', context)
    
def logout(request):
    request.session.flush()
    return redirect('/')

user/templates/user/forget_pw.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    비밀번호 찾기
</body>
</html>

user/templates/user/login backup.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="../../../static/login.js"></script>
    <link rel="stylesheet" href="../../../static/login.css">
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="card p-4">
            <h1 class="text-center mb-4">LOGIN</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {% for form in forms %}
                <div class="mb-3">
                    <label for="{{ form.id_for_label }}">{{ form.label }}</label>
                    {{ form }}
                </div>
                {% endfor %}
        
                {% if error %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
                {% endif %}
                <div class="text-center">
                    <button type="submit" class="btn btn-outline-dark" name="login-submit" value="login">로그인하기</button>
                </div>
            </form>
            <hr>
            <div class="text-center">
                <a href="{% url 'user:forgetid' %}" id="forget_id">Forget ID?</a>
                <span class="mx-4">|</span>
                <a href="{% url 'user:forgetpw' %}" id="forfet_pw">Forget Password?</a>
            </div>
        </div>
    </div>
</body>

</html>

user/templates/user/login.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="/static/css/basic.css" rel="stylesheet" >
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
	<div id="container" class="container">
		<!-- FORM SECTION -->
		<div class="row">
			<!-- SIGN UP -->
			<div class="col align-items-center flex-col sign-up">
				<div class="form-wrapper align-items-center">
					<div class="form sign-up">
						<form action="" method="POST">
							{% csrf_token %}
							{% for registerform in registerforms %}
							<div class="input-group">
								{{ registerform }}
							</div>
							{% endfor %}

							{% if registerforms_error %}
							<div class="alert alert-danger" role="alert">{{ registerforms_error }}</div>
							{% endif %}
							<div class="input-group">
								<button type="submit" name="register" value="register">회원가입하기</button>
							</div>
						</form>
						<p>
							<span>
								이미 계정이 있으신가요?
							</span>
							<b onclick="toggle()" class="pointer">
								로그인 하러 가기
							</b>
						</p>
					</div>
				</div>
			
			</div>
			<!-- END SIGN UP -->
			<!-- SIGN IN -->
			<div class="col align-items-center flex-col sign-in">
				<div class="form-wrapper align-items-center">
					<div class="form sign-in">
						<form action="" method="POST">
							{% csrf_token %}
							{% for loginform in loginforms %}
							<div class="input-group">
								{{ loginform }}
							</div>
							{% endfor %}
					
							{% if login_error %}
							<div class="alert alert-danger" role="alert">{{ login_error }}</div>
							{% endif %}
							<div class="input-group">
								<button type="submit" name="login" value="login">로그인하기</button>
							</div>
						</form>
						<p>
							<b>
								<a href="{% url  'user:reset_password' %}">Forgot password?</a>
							</b>
						</p>
						<p>
							<span>
								계정이 없으신가요?
							</span>
							<b onclick="toggle()" class="pointer">
								회원가입
							</b>
						</p>
					</div>
				</div>
				<div class="form-wrapper">
		
				</div>
			</div>
			<!-- END SIGN IN -->
		</div>
		<!-- END FORM SECTION -->
		<!-- CONTENT SECTION -->
		<div class="row content-row">
			<!-- SIGN IN CONTENT -->
			<div class="col align-items-center flex-col">
				<div class="text sign-in">
					<h2 style="font-size: 200px;">
						TODO
					</h2>
					<h2 class="text sign-in">
						<small style="color: black;">Join with us!</small>
					</h2>
	
				</div>
				<div class="img sign-in">
		
				</div>
			</div>
			<!-- END SIGN IN CONTENT -->
			<!-- SIGN UP CONTENT -->
			<div class="col align-items-center flex-col">
				<div class="img sign-up">
				
				</div>
				<div class="text sign-up">
					<h2>
						Join with us!
					</h2>
	
				</div>
			</div>
			<!-- END SIGN UP CONTENT -->
		</div>
		<!-- END CONTENT SECTION -->
	</div>
	<script src="/static/js/test.js" type="text/javascript"></script>
</body>

</html>

user/templates/user/login복사해올것.html
{% comment %} <!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="../../../static/login.js"></script>
    <link rel="stylesheet" href="../../../static/login.css">
</head>
<body>
    <div id="container" class="container">
        <!-- FORM SECTION -->
        <div class="row">
          <!-- SIGN UP -->
          <div class="col align-items-center flex-col sign-up">
            <div class="form-wrapper align-items-center">
              <div class="form sign-up">
                <div class="input-group">
                  <i class='bx bxs-user'></i>
                  <input type="text" placeholder="Username">
                </div>
                <div class="input-group">
                  <i class='bx bx-mail-send'></i>
                  <input type="email" placeholder="Email">
                </div>
                <div class="input-group">
                  <i class='bx bxs-lock-alt'></i>
                  <input type="password" placeholder="Password">
                </div>
                <div class="input-group">
                  <i class='bx bxs-lock-alt'></i>
                  <input type="password" placeholder="Confirm password">
                </div>
                <button>
                  Sign up
                </button>
                <p>
                  <span>
                    Already have an account?
                  </span>
                  <b onclick="toggle()" class="pointer">
                    Sign in here
                  </b>
                </p>
              </div>
            </div>
          
          </div>
          <!-- END SIGN UP -->
          <!-- SIGN IN -->
          <div class="col align-items-center flex-col sign-in">
            <div class="form-wrapper align-items-center">
              <div class="form sign-in">
                <div class="input-group">
                  <i class='bx bxs-user'></i>
                  <input type="text" placeholder="Username">
                </div>
                <div class="input-group">
                  <i class='bx bxs-lock-alt'></i>
                  <input type="password" placeholder="Password">
                </div>
                <button>
                  Sign in
                </button>
                <p>
                  <b>
                    Forgot password?
                  </b>
                </p>
                <p>
                  <span>
                    Don't have an account?
                  </span>
                  <b onclick="toggle()" class="pointer">
                    Sign up here
                  </b>
                </p>
              </div>
            </div>
            <div class="form-wrapper">
        
            </div>
          </div>
          <!-- END SIGN IN -->
        </div>
        <!-- END FORM SECTION -->
        <!-- CONTENT SECTION -->
        <div class="row content-row">
          <!-- SIGN IN CONTENT -->
          <div class="col align-items-center flex-col">
            <div class="text sign-in">
              <h2>
                Welcome
              </h2>
      
            </div>
            <div class="img sign-in">
        
            </div>
          </div>
          <!-- END SIGN IN CONTENT -->
          <!-- SIGN UP CONTENT -->
          <div class="col align-items-center flex-col">
            <div class="img sign-up">
            
            </div>
            <div class="text sign-up">
              <h2>
                Join with us
              </h2>
      
            </div>
          </div>
          <!-- END SIGN UP CONTENT -->
        </div>
        <!-- END CONTENT SECTION -->
    </div>
</body>
</html> {% endcomment %}

user/templates/user/myinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My info</title>
</head>
<body>
    <h1>내 정보</h1>
    <p>이름: {{ user_name }}</p>
    <p>아이디: {{ user_id }}</p>
    <p>이메일: {{ user_email }}</p>
    <a href="#"><p>현재 비밀번호 변경</p></a>
</body>
</html>

user/templates/user/password_reset.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>Send Recovery Email</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <h3 class="text-center mt-4">Password reset</h3>
    <p>
        forgotten your password?
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="Send email">
    </form>
</body>
</html>

user/templates/user/password_reset_done.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script> -->
</head>
<body>
    <p>이메일로 전송했습니다 성공적으로 재설정되었습니다. 새로운 비밀번호로 로그인해주세요.</p>
    <a href="/"> 로그인 </a>
</body>
</html>

user/templates/user/password_reset_form.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>Send Recovery Email</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <h3 class="text-center mt-4">Password reset</h3>
    <p>
        forgotten your password?
    </p>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="Send email">
    </form>
</body>
</html>

user/templates/user/password_reset_sent.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <h3>이메일을 보냈다</h3>
    <p> 확인 바란다 </p>
</body>
</html>

user/templates/user/register.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <title>TO_DO_page!</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
        <div class="card p-5">
            <h1 class="text-center mb-4">REGISTER</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {% for form in forms %}
                <div class="mb-3">
                    <label for="{{ form.id_for_label }}">{{ form.label }}</label>
                    {{ form }}
                </div>
                {% endfor %}
                
                {% if error %}
                <div class="alert alert-danger">{{ error }}</div>
                {% endif %}
                <div>
                    <button type="submit" class="btn btn-outline-dark" name="register-submit" value="register">회원가입하기</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>